using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Tera.Libs.Enumerations
{
    public enum EffectEnum
    {
        None = -1,

        // Armures
        AddArmorNeutre,
        AddArmorTerre,
        AddArmorFeu,
        AddArmorEau,
        AddArmorAir,

        MaximizeEffects = 782,
        MinimizeEffects = 781,

        Teleport = 4,
        PushBack = 5,
        PushFront = 6,
        Transpose = 8,
        MissBack = 9,
        DamageBrut,

        TurnPass = 140,
        DieFighter = 141,
        DieFighterReplaceInvocation = 405,

        VolPM = 77,
        BonusPM = 78,
        ChanceEcaflip = 79,

        RenderedPDV = 81,
        HealOnAttack = 786,
        VolVie = 82,
        VolPA = 84,
        VolChance = 266,
        VolVita = 267,
        VolAgi = 268,
        VolIntell = 269,
        VolSagesse = 270,
        VolForce = 271,

        DamageLifeEau = 85,
        DamageLifeTerre = 86,
        DamageLifeAir = 87,
        DamageLifeFeu = 88,
        DamageLifeNeutre = 89,

        DamageLifePercentNeutre = 671,
        DamageLifePercentNeutre2 = 670,
        DamageLifePercentNeutre3 = 672,

        DamageLifeMissingEau = 275,
        DamageLifeMissingTerre = 276,
        DamageLifeMissingAir = 277,
        DamageLifeMissingFeu = 278,
        DamageLifeMissingNeutre = 279,

        DamageDropLife = 90,
        VolEau = 91,
        VolTerre = 92,
        VolAir = 93,
        VolFeu = 94,
        VolNeutre = 95,
        DamageEau = 96,
        DamageTerre = 97,
        DamageAir = 98,
        DamageFeu = 99,
        DamageNeutre = 100,
        AddArmor = 105,
        AddArmorBis = 265,

        AddRenvoiDamageItem = 220,
        ReflectSpell = 106,
        AddRenvoiDamage = 107,
        Heal = 108,
        DamageLanceur = 109,
        AddVie = 110,
        AddPA = 111,
        AddDamage = 112,
        AddDamageBis = 121,
        DoubleDamageOrRendPDV = 113,
        MultiplyDamage = 114,

        AddCC = 115,
        SubCC = 171,

        AddPABis = 120,
        AddAgilite = 119,
        AddChance = 123,
        AddDamagePercent = 138,
        AddEnergy = 139,
        SubDamagePercent = 186,
        SubDamagePercentBis = 164,
        AddDamageCritic = 115,
        AddDamagePiege = 225,
        AddDamagePiegePercent = 226,
        AddDamagePhysic = 142,
        AddDamageMagic = 143,
        AddEchecCritic = 122,
        AddEsquivePA = 160,
        AddEsquivePM = 161,
        AddForce = 118,
        AddInitiative = 174,
        AddIntelligence = 126,
        AddInvocationMax = 182,
        AddPM = 128,
        AddPO = 117,
        AddPods = 158,
        StealMoney = 130,
        AddProspection = 176,
        AddSagesse = 124,
        AddSoins = 178,
        AddVitalite = 125,
        SubAgilite = 154,

        ResurrectAlly = 147,
        Damage = 144,

        Transform = 197,

        DamagePerPA = 131,
        IncreaseSpellDamage = 293,
        Maitrise = 165,
        VolPO = 320,
        Punition = 672,
        Sacrifice = 765,

        SubChance = 152,
        SubDamage = 145,
        SubDamageCritic = 171,
        SubDamageMagic = 172,
        SubDamagePhysic = 173,
        SubEsquivePA = 162,
        SubEsquivePM = 163,
        SubForce = 157,
        SubInitiative = 175,
        SubIntelligence = 155,
        SubPAEsquivable = 101,
        SubPMEsquivable = 127,
        SubPA = 168,
        SubPM = 169,
        SubPO = 116,
        SubPods = 159,
        SubProspection = 177,
        SubSagesse = 156,
        SubSoins = 179,
        SubVitalite = 153,

        InvocDouble = 180,
        Invocation = 181,
        InvocationStatic = 185,

        AddReduceDamagePhysic = 183,
        AddReduceDamageMagic = 184,

        AddReduceDamagePourcentEau = 211,
        AddReduceDamagePourcentTerre = 210,
        AddReduceDamagePourcentAir = 212,
        AddReduceDamagePourcentFeu = 213,
        AddReduceDamagePourcentNeutre = 214,
        AddReduceDamagePourcentPvPEau = 251,
        AddReduceDamagePourcentPvPTerre = 250,
        AddReduceDamagePourcentPvPAir = 252,
        AddReduceDamagePourcentPvPFeu = 253,
        AddReduceDamagePourcentPvPNeutre = 254,

        AddReduceDamageEau = 241,
        AddReduceDamageTerre = 240,
        AddReduceDamageAir = 242,
        AddReduceDamageFeu = 243,
        AddReduceDamageNeutre = 244,
        AddReduceDamagePvPEau = 261,
        AddReduceDamagePvPTerre = 260,
        AddReduceDamagePvPAir = 262,
        AddReduceDamagePvPFeu = 263,
        AddReduceDamagePvPNeutre = 264,

        SubReduceDamagePourcentEau = 216,
        SubReduceDamagePourcentTerre = 215,
        SubReduceDamagePourcentAir = 217,
        SubReduceDamagePourcentFeu = 218,
        SubReduceDamagePourcentNeutre = 219,
        SubReduceDamagePourcentPvPEau = 255,
        SubReduceDamagePourcentPvPTerre = 256,
        SubReduceDamagePourcentPvPAir = 257,
        SubReduceDamagePourcentPvPFeu = 258,
        SubReduceDamagePourcentPvpNeutre = 259,
        SubReduceDamageEau = 246,
        SubReduceDamageTerre = 245,
        SubReduceDamageAir = 247,
        SubReduceDamageFeu = 248,
        SubReduceDamageNeutre = 249,

        CasterSubPA = 133,
        CasterSubPM = 134,
        CasterSubPO = 135,
        CasterAddPO = 136,
        CasterAddDamagePhysic = 137,


        Porter = 50,
        Lancer = 51,
        Perception = 202,
        ChangeSkin = 149,
        UseTrap = 400,
        UseGlyph = 401,
        UseBlyph = 402,
        DoNothing = 666,
        PushFear = 783,
        AddChatiment = 788,
        AddState = 950,
        LostState = 951,
        Invisible = 150,
        DeleteAllBonus = 132,


        /* Parchemins */
        AddSpell = 604,
        AddCharactForce = 607,
        AddCharactSagesse = 678,
        AddCharactChance = 608,
        AddCharactAgilite = 609,
        AddCharactVitalite = 610,
        AddCharactIntelligence = 611,
        AddCharactPoint = 612,
        AddSpellPoint = 613,

        InvocInfo = 628,

        SoulStoneStats = 705,
        MountCaptureProba = 706,

        SoulCaptureBonus = 750,
        MountExpBonus = 751,

        LastEat = 808,

        AlignementId = 960,
        AlignementGrade = 961,
        TargetLevel = 962,
        CreateTime = 963,
        TargetName = 964,
        
        MountOwner = 995,
        MountOwnerName = 996,
        MountName = 997,

        LivingGfxId = 970,
        LivingMood = 971,
        LivingSkin = 972,
        LivingType = 973,
        LivingXp = 974,
        ReceivedDate = 805,

        CanBeExchange = 983,
    }
}
